Crud/Crud/urls.py
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

Crud/myapp/urls.py
from django.urls import path
from myapp import views

app_name='myapp'
urlpatterns = [
    path('',views.index,name='index' ),
    path('student_form/',views.student_form,name='student_form' ),
    path('student_info/<int:student_id>/',views.student_info,name='student_info' ),
    path('student_update/<int:student_id>/', views.student_update, name='student_update'),
    path('student_delete/<int:student_id>/',views.student_delete,name='student_delete' ),
]

Crud/myapp/models.py
from django.db import models


# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()

    def __str__(self):
        return str(self.pk)+""+ self.first_name+" "+ self.last_name

Crud/myapp/forms.py
from django import forms
from . import models


class StudentForm(forms.ModelForm):
    class Meta:
        model = models.Student
        fields = "__all__"

Crud/myapp/views.py
from django.shortcuts import render
from .forms import StudentForm
from .models import Student


# Create your views here.

def index(request):
    student_list = Student.objects.order_by('pk')
    diction = {'title': 'Index', 'student_list': student_list}
    return render(request, 'myapp/index.html', context=diction)


def student_form(request):
    form = StudentForm()
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction = {'title': 'Student Form', 'student_form': form}
    return render(request, 'myapp/student_form.html', context=diction)


def student_info(request, student_id):
    student_info = Student.objects.get(pk=student_id)
    diction = {'student_info': student_info}
    return render(request, 'myapp/student_info.html', context=diction)

def student_update(request,student_id):
    student_info=Student.objects.get(pk=student_id)
    form=StudentForm(instance=student_info)
    if request.method=='POST':
        form=StudentForm(request.POST,instance=student_info)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction={'student_update':form}
    return render(request,'myapp/student_update.html',context=diction)


def student_delete(request,student_id):
    student_list = Student.objects.get(pk=student_id).delete()
    diction = {'delete_message':'DELETED'}
    return render(request, 'myapp/student_delete.html', context=diction)

Crud/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'myapp:index' %}">Index</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myapp:student_form' %}">Student Form <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Crud/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body %}
    <h1>Student List </h1>
    <ul>
        {% if student_list %}

            {% for student in student_list %}
             <li><a href="{% url 'myapp:student_info' student_id=student.id %}">{{student.first_name}} {{student.last_name}}</a></li>
            {% endfor %}

        {% else %}
         <h2>No student</h2>
        {% endif %}
    </ul>
{% endblock %}

Crud/templates/myapp/student_delete.html
{% extends 'myapp/base.html' %}
{% block body %}
<div class="alert alert-danger">{{delete_message}}</div>
{% endblock %}

Crud/templates/myapp/student_form.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="text-center">
           <h1 style=" color:blue" >Student Form </h1>
        <form method="POST">
            {{student_form.as_p}}
            {% csrf_token %}
            <input type="submit" name="submit" value="Add Student   " class="btn btn-primary">


        </form>

    </div>
{% endblock %}

Crud/templates/myapp/student_info.html
{% extends 'myapp/base.html' %}

{% block body %}
<h1>student info</h1>
<h2>Name:{{student_info.first_name}} {{student_info.last_name}}</h2>
<h2>Email:{{student_info.email}}</h2>
<h2>Phone:{{student_info.phone}}</h2>

<a class="btn btn-primary" href="{% url 'myapp:student_update' student_id=student_info.id %}">Update</a>
<a class="btn btn-primary" href="{% url 'myapp:student_delete' student_id=student_info.id %}">Delete</a>

{% endblock %}

Crud/templates/myapp/student_update.html
{% extends 'myapp/base.html' %}

{% block body %}
<div class="text-center">
           <h1 style=" color:blue" >Student Update </h1>
        <form method="POST">
            {{student_update.as_p}}
            {% csrf_token %}
            <input type="submit" name="submit" value="Update" class="btn btn-primary">

        </form>
</div>

{% endblock %}